### ISSUE TITLE
Offtopic - Maybe another plugin?

### ISSUE THREAD

**Issue by javiavid** [k4a-dev/obsidian-heading-shifter#2]
Hi, 
I didn't know where to propose it, but when I saw your plugin I thought of something that I've been waiting for a long time and nobody does.

I think it would be very interesting to do something similar with the images, there is no easy way to reduce or increase the size of the images in the document in a dynamic way.

I usually use the replace option to change all images at once:
![](image.jpg)

for this:
![300](image.jpg)

But if you need to adjust only a few specific images it is a slow and manual process.

I think some part of your code for heading shifter could be used to get something similar but with images.

**Comment by k4a-dev** [comment]
Hello,
I think it would be easy to develop it, leaving aside whether to use part of this code or not.

However, I don't want that plugin because I never specify image size in Markdown.

Heading Size is a component of document structure, but Image Size is only a component of appearance, not the essence of document structure.

**Comment by javiavid** [comment]
Thanks for the reply
